packages:
  # all applications in direct subdirs of apps/
  - 'apps/*'
  # all proof of concept in direct subdirs of pocs/
  - 'packages/*'
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'